title: "MrLearner0204 - Malware Researcher"
description: "Windows Security Researcher | Malware Analyst | Reverse Engineer"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
google_analytics:
markdown: kramdown

# Customization
header_pages:
  - about.md
  - malware-analysis.md
  - maldev-projects.md
  
# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
